import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import Image from "next/image";
import AppSidebar from "@/components/layout/AppSidebar";
import { redirect } from "next/navigation";
import { Toaster } from "react-hot-toast";
import mongoose from "mongoose";
import { Page } from "@/models/page";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faLink } from "@fortawesome/free-solid-svg-icons";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppTemplate({ children, ...rest }) {
    const session = await getServerSession(authOptions);
    if (!session) {
        return redirect('/');
    }
    mongoose.connect(process.env.MONGODB_URI);
    const page = await Page.findOne({owner: session.user.email});
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <main className="md:flex min-h-screen">
            <aside className="bg-white w-48 p-4 pt-6 shadow">
              <div className="sticky top-0 pt-2">
                <div className="rounded-full overflow-hidden aspect-square w-24 mx-auto">
                    <Image src={session.user.image} width={256} height={256} alt={'avatar'} />
                </div>
                {page && (
                  <Link 
                    target="_blank"
                    href={'/'+page.uri}
                    className="text-center mt-4 flex gap-1 items-center justify-center">
                    <FontAwesomeIcon size="lg" icon={faLink} className="text-blue-500" />
                    <span className="text-xl text-gray-300">/</span>
                    <span>{page.uri}</span>
                  </Link>
                )}
                <div className="text-center">
                <AppSidebar />
                </div>
                </div>
            </aside>
            <div className="grow">
            {children}
            </div>
        </main>
      </body>
    </html>
  );
}
